# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{resque-multi-step}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Williams", "Morgan Whitney"]
  s.date = %q{2010-10-04}
  s.description = %q{Provides multi-step tasks with finalization and progress tracking}
  s.email = %q{pezra@barelyenough.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/resque-multi-step.rb",
     "lib/resque/plugins/multi_step_task.rb",
     "lib/resque/plugins/multi_step_task/assure_finalization.rb",
     "lib/resque/plugins/multi_step_task/atomic_counters.rb",
     "lib/resque/plugins/multi_step_task/constantization.rb",
     "lib/resque/plugins/multi_step_task/finalization_job.rb",
     "lib/resque_mutli_step.rb",
     "resque-multi-step-task.gemspec",
     "spec/acceptance/acceptance_jobs.rb",
     "spec/acceptance/job_handling_spec.rb",
     "spec/acceptance/spec_helper.rb",
     "spec/resque-multi-step_spec.rb",
     "spec/resque/plugins/multi_step_task/finalization_job_spec.rb",
     "spec/resque/plugins/multi_step_task_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/pezra/resque-multi-step}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Provides multi-step tasks with finalization and progress tracking}
  s.test_files = [
    "spec/acceptance/acceptance_jobs.rb",
     "spec/acceptance/job_handling_spec.rb",
     "spec/acceptance/spec_helper.rb",
     "spec/resque/plugins/multi_step_task/finalization_job_spec.rb",
     "spec/resque/plugins/multi_step_task_spec.rb",
     "spec/resque-multi-step_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<redis-namespace>, ["~> 0.8.0"])
      s.add_runtime_dependency(%q<resque>, ["~> 1.10"])
      s.add_runtime_dependency(%q<resque-fairly>, ["~> 1.0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<redis-namespace>, ["~> 0.8.0"])
      s.add_dependency(%q<resque>, ["~> 1.10"])
      s.add_dependency(%q<resque-fairly>, ["~> 1.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<redis-namespace>, ["~> 0.8.0"])
    s.add_dependency(%q<resque>, ["~> 1.10"])
    s.add_dependency(%q<resque-fairly>, ["~> 1.0"])
  end
end

