# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "resque-multi-step"
  s.version = "2.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Williams", "Morgan Whitney"]
  s.date = "2014-02-05"
  s.description = "Provides multi-step tasks with finalization and progress tracking"
  s.email = "pezra@barelyenough.org"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "History.txt",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/resque-multi-step.rb",
    "lib/resque/plugins/multi_step_task.rb",
    "lib/resque/plugins/multi_step_task/assure_finalization.rb",
    "lib/resque/plugins/multi_step_task/atomic_counters.rb",
    "lib/resque/plugins/multi_step_task/constantization.rb",
    "lib/resque/plugins/multi_step_task/finalization_job.rb",
    "lib/resque_mutli_step.rb",
    "resque-multi-step.gemspec",
    "spec/acceptance/acceptance_jobs.rb",
    "spec/acceptance/job_handling_spec.rb",
    "spec/acceptance/spec_helper.rb",
    "spec/resque-multi-step_spec.rb",
    "spec/resque/plugins/multi_step_task/finalization_job_spec.rb",
    "spec/resque/plugins/multi_step_task_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/pezra/resque-multi-step"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Provides multi-step tasks with finalization and progress tracking"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<resque-multi-step>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<redis-namespace>, [">= 0"])
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<resque>, [">= 0"])
      s.add_runtime_dependency(%q<resque-fairly>, [">= 0"])
    else
      s.add_dependency(%q<resque-multi-step>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<redis-namespace>, [">= 0"])
      s.add_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_dependency(%q<resque>, [">= 0"])
      s.add_dependency(%q<resque-fairly>, [">= 0"])
    end
  else
    s.add_dependency(%q<resque-multi-step>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<redis-namespace>, [">= 0"])
    s.add_dependency(%q<yajl-ruby>, [">= 0"])
    s.add_dependency(%q<resque>, [">= 0"])
    s.add_dependency(%q<resque-fairly>, [">= 0"])
  end
end

